# Generated by Django 6.0.2 on 2026-02-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_domain', models.CharField(max_length=255, unique=True)),
                ('access_token', models.CharField(max_length=255)),
                ('delivery_customization_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('disable_cod_min_cart', 'Disable COD below cart value'), ('disable_cod_region', 'Disable COD for region'), ('add_cod_fee', 'Add COD fee'), ('hide_shipping', 'Hide shipping method')], max_length=50)),
                ('min_cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_fee_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_fee_is_percent', models.BooleanField(default=False)),
                ('shipping_method_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.shop')),
            ],
        ),
    ]
