# Generated by Django 6.0.2 on 2026-02-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='condition_type',
            field=models.CharField(choices=[('and', 'All conditions must match (AND)'), ('or', 'Any condition can match (OR)')], default='and', max_length=10),
        ),
    ]
