# Generated by Django 6.0.2 on 2026-02-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rule_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('disable_cod_min_cart', 'Disable COD below cart value'), ('disable_cod_region', 'Disable COD for region'), ('add_cod_fee', 'Add COD fee'), ('hide_shipping', 'Hide shipping method'), ('hide_payment', 'Hide payment method')], max_length=50),
        ),
    ]
