# Generated by Django 6.0.2 on 2026-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rule_payment_method_name_alter_rule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro')], default='Free', max_length=10),
        ),
    ]
