# Generated by Django 6.0.2 on 2026-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shop_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('hide_shipping', 'Hide shipping method'), ('hide_payment', 'Hide payment method')], max_length=50),
        ),
    ]
