# Generated by Django 6.0.2 on 2026-03-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rule_summary_alter_rule_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
