# Generated by Django 6.0.2 on 2026-03-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rule_rule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='shopify_delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rule',
            name='shopify_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
